version: '3'
services:
  pocket_wallet_web:
    container_name: pocket_wallet_web
    build: ./
    hostname: web
    ports:
      - "8002:8002"
    env_file:
      - "envfile"
networks:
  default:
    external:
      name: websites
