version: '3'
services:
  pocket_wallet_web:
    container_name: pocket_wallet_web
    build: ./
    hostname: web
    ports:
      - "8005:8005"
networks:
  default:
    external:
      name: websites
